server:
  port: 4002

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: patient-service-route
          uri: http://patient-service:4000
          predicates:
            - path=/api/patients/**
          filters:
            - strip-prefix=1

#        route for api-docs of patient service
        - id: api-docs-patient-route
          uri: http://patient-service:4000
          predicates:
            - path=/api-docs/patients
          filters:
            - RewritePath=/api-docs/patients,/v3/api-docs
