### PUT request to update a patient
PUT http://localhost:4000/patients/c71c6c08-429f-415f-a4c9-66371d208391
Content-Type: application/json

{
  "name": "Oliver Scott Updated",
  "email": "oliver.scott.updated@example.com",
  "address": "111 Aspen St, Hilltown, Updated",
  "dateOfBirth": "1983-05-27"
}

###